services:
  thsr-sniper:
    build: .
    image: seanchangx/thsr-sniper:latest
    container_name: thsr-sniper
    # volumes:
    #   - ./tmp:/tmp/
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY:-:0}
      - TERM=xterm-256color
    network_mode: host
    stdin_open: true
    tty: true
    command: bash
