services:
  thsr-sniper:
    build: .
    image: seanchangx/thsr-sniper:latest
    container_name: thsr-sniper
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY:-:0}
      - TERM=xterm-256color
      - THSR_FORCE_INTERACTIVE=1  # Force interactive mode for pure CLI usage
    network_mode: host
    stdin_open: true
    tty: true
    command: bash
    restart: unless-stopped

  scheduler:
    build: .
    image: seanchangx/thsr-sniper:latest
    container_name: thsr-scheduler
    volumes:
      - thsr_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
    restart: unless-stopped
    command: python watchdog.py

  api:
    build: .
    image: seanchangx/thsr-sniper:latest
    container_name: thsr-api
    ports:
      - "8000:8000"
    volumes:
      - thsr_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python main.py --start-api --api-host 0.0.0.0 --api-port 8000

volumes:
  thsr_data:
    driver: local
